/* auto-generated: do not edit */
#include <stdint.h>
const char g_theme_default_kth[] =
"[desktop]\n"
"bg = #7c0034ff\n"
"\n"
"[window]\n"
"bg            = #E6E6E6\n"
"border        = #B0B0B0\n"
"title_bg      = #ffffffff\n"
"title_text    = #000000ff\n"
"corner_radius = 10\n"
"\n"
"[dock]\n"
"bg              = #202020cc\n"
"border          = #404040ff\n"
"icon_bg         = #303030ff\n"
"icon_hover_bg   = #505050ff\n"
"\n"
"height          = 56\n"
"radius          = 28\n"
"padding         = 12\n"
"icon_size       = 32\n"
"spacing         = 10\n"
"position        = center   ; left | center | right\n"
"auto_hide       = 0\n"
"\n"
"\n"
"button_style  = traffic\n"
"button_size   = 12\n"
"button_gap    = 16\n"
"button_margin = 6\n"
"\n"
"button_layout = right\n"
"button_order  = close,max,min\n"
"\n"
"button_padding_right = 8\n"
"button_padding_left  = 8\n"
"\n"
"title_align   = left\n"
"title_padding_left = 10\n"
"title_padding_right = 10\n"
"\n"
"btn_close_color = #FF5F57\n"
"btn_max_color   = #28C840\n"
"btn_min_color   = #FEBC2E\n"
"\n"
"btn_hover_mul   = 0.85\n"
"btn_press_mul   = 0.70\n"
"\n"
"[textbox]\n"
"bg            = #EFEFEF\n"
"border        = #AAAAAA\n"
"focus_border  = #5080FF\n"
"text          = #000000\n"
"placeholder   = #888888\n"
"caret         = #000000\n"
"\n"
"[button]\n"
"bg            = #C8C8C8\n"
"border        = #646464\n"
"hover_bg      = #DCDCDC\n"
"hover_border  = #505050\n"
"pressed_bg    = #B4B4B4\n"
"pressed_border= #3C3C3C\n"
"text          = #000000\n"
;
